title: Manish Sharma
logo: /assets/img/DSC_8871.JPG
description: Currently working as a Junior Reserach Fellow in Bennett University.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
